name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system libs for PyAV
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg \
            libavdevice-dev libavfilter-dev libavformat-dev \
            libavcodec-dev libavutil-dev libswscale-dev libavresample-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q
